- name: Establish Proxmox7 Repositories
  hosts: proxmox_nodes

  tasks:
    - name: Update apt sources with pve7
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: "{{ item }}"
        state: present
        mode: 0644
      loop:
      - deb http://ftp.debian.org/debian bullseye main contrib
      - deb http://ftp.debian.org/debian bullseye-updates main contrib
      - deb http://security.debian.org/debian-security bullseye-security main contrib
      - deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription

    - name: Remove duplicate pve7 source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        line: deb http://security.debian.org bullseye-security main contrib
        state: absent
        mode: 0644

    - name: Remove pve7 enterprise source
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        line: deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise
        state: absent
        mode: 0644
